<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-GRKK7EO" failures="1" tests="6" name="practice.testng.CreateContactRetryListenerTest" time="0.027" errors="0" timestamp="2024-05-20T16:30:17 BST" skipped="5">
  <testcase classname="practice.testng.CreateContactRetryListenerTest" name="createContactTest" time="0.001">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:92)
at org.junit.Assert.assertTrue(Assert.java:43)
at org.junit.Assert.assertTrue(Assert.java:54)
at practice.testng.CreateContactRetryListenerTest.createContactTest(CreateContactRetryListenerTest.java:12)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- createContactTest -->
  <system-out/>
  <testcase classname="practice.testng.CreateContactRetryListenerTest" name="createContactTest" time="0.002">
    <skipped/>
  </testcase> <!-- createContactTest -->
  <system-out/>
  <testcase classname="practice.testng.CreateContactRetryListenerTest" name="createContactTest" time="0.002">
    <skipped/>
  </testcase> <!-- createContactTest -->
  <system-out/>
  <testcase classname="practice.testng.CreateContactRetryListenerTest" name="createContactTest" time="0.002">
    <skipped/>
  </testcase> <!-- createContactTest -->
  <system-out/>
  <testcase classname="practice.testng.CreateContactRetryListenerTest" name="createContactTest" time="0.002">
    <skipped/>
  </testcase> <!-- createContactTest -->
  <system-out/>
  <testcase classname="practice.testng.CreateContactRetryListenerTest" name="createContactTest" time="0.018">
    <skipped/>
  </testcase> <!-- createContactTest -->
  <system-out/>
</testsuite> <!-- practice.testng.CreateContactRetryListenerTest -->
